POST http://localhost:3001/api/partners/register HTTP/1.1
content-type: application/json

{
    "email":"pedro@gmail.com",
    "nameResponsavel":"brener",
    "nameFantasia":"FATEC",
    "cnpj":"123456789",
    "password":"123"
}