POST http://localhost:3001/api/users/register HTTP/1.1
content-type: application/json

{
    "email":"alberto@gmail.com",
    "name":"alberto",
    "lastName":"1",
    "number":"28",
    "sexo":"Masc",
    "cpf":"123456789",
    "address":"endereço",
    "password":"123"
}