POST http://localhost:3001/api/partners/register HTTP/1.1
content-type: application/json

{
    "email":"brener@gmail.com",
    "nameFantasia":"Brener",
    "nameResponsavel":"Freire",
    "cnpj":"321321321",
    "password":"123"
}


